spring:
  application:
    name: todo
  datasource:
    url: jdbc:h2:mem:tododb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false